services:
  backend:
    build: .
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-6} # Default is 6
    env_file:
      - .env
  
  backend-clear:
    build:
      context: .
      dockerfile: Dockerfile.clear
    env_file:
      - .env
